### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by zerogerc** [ZeRoGerc/cpp_proxy#1]
- [x] caching
- [x] disconnect by timer
- [x] soft and hard close
- [x] wrap for std::thread
- [x] http parser
- [ ] https
